### ISSUE TITLE
labs_mapping.pkl unknown

### ISSUE THREAD

**Issue by blwowski** [fursovia/tcav_nlp#2]
In the file calculate_tcav.py lines 17-18 you load a pickle file called `labs_mapping.pkl`. I do not see this created anywhere in the code. Could you help me understand where this comes from?

**Comment by fursovia** [comment]
Hi @blwowski 

It's just a dict that maps your labels to unique `ID`s. 

```python
labs_mapping = {lab: i for i, lab in enumerate(data['labels'].unique())}
```

Take a look at this notebook for an example (https://github.com/fursovia/tcav_nlp/blob/master/notebooks/lenta_dataset.ipynb)
